default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = nil
    if ENV["ASC_KEY_ID"]
      api_key = app_store_connect_api_key(
        key_id: ENV["ASC_KEY_ID"],
        issuer_id: ENV["ASC_ISSUER_ID"],
        key_filepath: ENV["ASC_KEY_PATH"]
      )
    end

    build_app(
      project: "App.xcodeproj",
      scheme: "App",
      export_method: "app-store",
      export_options: {
        teamID: "Z88477N5ZU",
        signingStyle: "automatic"
      },
      xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
